### ISSUE TITLE
Improve mocking in tests

### ISSUE THREAD

**Issue by MartinSkovsen** [pruner/cli#4] opened 2020-11-06 09:25 UTC

**Comment by ffMathy** [comment] 2020-12-10 13:04
Hmmm I have given this some extra thought, and I don't actually think it's desirable. The problem is that it'll introduce a weird import-like pseudo-syntax. The current proposal actually seems cleaner.

@MartinSkovsen what are your thoughts?

**Comment by ffMathy** [comment] 2020-12-12 11:01
Closing until I get a reply.

**Closed by ffMathy** 2020-12-12 11:01 UTC
Labels: enhancement, tests
